name: mikeee-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - v1.15

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.105.0'
          extended: true
    
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Install npm deps
        working-directory: ./daprdocs
        run: npm install
          
      - name: Setup Docsy
        working-directory: ./daprdocs
        run: git submodule update --init --recursive && sudo npm install autoprefixer -g && sudo npm install postcss-cli -g

      - name: Build
        env:
          HUGO_VERSION: "0.105.0"
        run: |
          hugo \
            --source ./daprdocs \
            --baseURL "${{ steps.pages.outputs.base_url }}/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./daprdocs/public

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
