name: mikeee-deploy

on:
  workflow_dispatch:
  push:
    branches:
      - v1.15

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.100.2'
          extended: true
    
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Install npm deps
        working-directory: ./daprdocs
        run: npm install
          
      - name: Setup Docsy
        working-directory: ./daprdocs
        run: git submodule update --init --recursive && sudo npm install -D --save autoprefixer && sudo npm install -D --save postcss-cli

      - name: Build
        env:
          HUGO_ENV: production
          HUGO_VERSION: "0.100.2"
        run: hugo --source ./daprdocs

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
